project_id = "hiayegpvrsxhhemyxghz"

[functions.fetch-rss-news]
verify_jwt = false

[functions.newsletter-run]
verify_jwt = false

[functions.image-proxy]
verify_jwt = false

[functions.cleanup-image-cache]
verify_jwt = false

[functions.manage-subscribers]
verify_jwt = false

[functions.unsubscribe]
verify_jwt = false

[functions.newsletter-track]
verify_jwt = false
